apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: pva2mxuqm-nodejs 
  janus-idp.io/tekton: pva2mxuqm-nodejs
  backstage.io/kubernetes-id: pva2mxuqm-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pva2mxuqm-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  